
; before decimal values of keys are posible two prefixes "U:" or "D:".
; If is defined the prefix "U:" key is send only by WM_KEYUP message.
; If is defined the prefix "D:" key is send only by WM_KEYDOWN message.
; In other cases are keys send by both messages. 

; after decimal values of keys is posible specify scancode of key 

; Example:
; VkLeft=	U:037:080
; Only by WM_KEYDOWN is send key with value 0x25 and scancode 0x50

[Common]
;//////////////////////////////////
;F1 = 0x70
VkAction1=	112	
;F2 = 0x71
VkAction2=	113	

;Special input mode switch "ALT"
VkInputSpec=	000
	

;backspace = 0x08
VkBack=		008

;tab = 0x09
VkTab=		009
	
;enter = 0x0D
VkEnter=	013	

;Shift = 0x10
VkShift=	016	


;left arrow = 0x25
VkLeft=		037	
;right arrow = 0x27
VkRight=	039	
;up arrow = 0x26
VkUp=		038
;down arrow = 0x28
VkDown=		040

;
VkVolumeUp=	000

;
VkVolumeDown=	000

;
VkZoomIn=	120

;
VkZoomOut=	119

;
VkEscape=	000

;
VkFind=		000

;
VkMenu=		000

;
VkSaveLocation=	000

;
Vk3D2D=		000

;
VkRotate=	000

;
VkExit=		000

; keys on numpad values from 0x60 to 0x69
VkHwKey0=	048	
VkHwKey1=	049
VkHwKey2=	050
VkHwKey3=	051
VkHwKey4=	052
VkHwKey5=	053
VkHwKey6=	054
VkHwKey7=	055
VkHwKey8=	056
VkHwKey9=	057
ImeOff=false
;/////////////End of common section /////


[MotoQ]
; Motorola MotoQ 

VkInputSpec=	145

;F7
VkZoomIn=	040:11

;F6
VkZoomOut=	038:10
;//////////////////////////////////////


[SGH-i600]
; Samsung SGH-i600

;
VkInputSpec=	144

;//////////////////////////////////////


[HTC_730]
; 
ImeOff=true

;//////////////////////////////////////
;//////////////////////////////////////


[HTC_710]
; 
ImeOff=true

;//////////////////////////////////////
;//////////////////////////////////////

[X1i]
VkAction1=	194	
VkAction2=	195	

;//////////////////////////////////////
;//////////////////////////////////////