[Application]
title=Sygic DRIVE
name=Sygic
version=704400
fps=8.0
; Define custom splash screen
;splash=yourlogo
; bacground color of spash screen (hex), defaul = 000000 black
splashBgr=#000000
; If true center image of splash is stretched
CenterStretch=false
; Move center image of splash screen to different position (TL, TR, BL, BL) C = no moving
CenterMove=C

memory=high
swVersion=7.71.10095
; topMost=true  ->  no other application will appear above navigation
; topMost=false ->  other applications (e.g. MP3 player) can be displayed above navigation window
topMost=false

[Drivers]
; Select driver (defines assignment of keys, backlight, com port handling and more)
Driver=Default\driver.dll

; Do not use the below
Device=Default\device.dll

[Default]
; com=[COM1:,9600 | autodetect]
com=COM1:,9600
; tmc=[COM3:,38400 | autodetect]

; antialiasing means displaying smooth maps. Setting it to 'true' can rapidly slow down some devices
antialias=true

; initially turning on (poiVisible=true) or off (poiVisible=false) some POI categories
poiVisible=false

[Settings]
processing=fribidi
showSafetyMsg=true

;Set color mode for output Display default mode is RGB565 other are RGB555 and BGR555
colorMode=RGB565

; In case of multiple platforms, when sharing of Resources is required.
; Path to folder with resources (GpsLogs, Icons, Itinerary, Skin, Sounds, Voices)
ResourcePath=\..\..\res
; Path to folder with maps
MapPath=\..\..\maps

; Settnings for First run wizard

;enable new VOlume system
NewVolumeSys=false
;MaxSpeed=190
;VolumeFactor=2.0
;select *.lang file from Skin folder
language=portuguese_br.lang
languageAsk=false

;select folder name from Voices folder
voice=portuguese_br_woman
voiceAsk=false

;select one of kilometer or mile
unit=kilometer
unitAsk=false

;select one of europe, us or uk
time=europe
timeAsk=false

;select one of degrees, minutes or seconds
coords=degrees
coordsAsk=false

;use combination of digits
;1=ROMAN 2=CYRILLIC 3=GREEK 4=ARABIC 5=HEBREW 6=THAI 7=JAPANESE 8=CHINESE 9=KOREAN
keybList=1
keybListsAsk=false

;select one of QWERTY, QWERTZ or AZERTY
keybTypeRoman=QWERTY

;select one of PINYIN, ZHUYIN, HANDWRITE or NONE
keybTypeChinese=NONE

;select name of *.mlm file
map=Brazil.mlm
mapAsk=false

;select coordinates for first run of Browse map

;Latitude in deggrees: Zero  = Equator, +90 = North Pole, -90 South Pole
;BrowseMapLat=+49.0

;Longitude in degrees: Zero is Greenwich + East, - West,+180 = -180 = International date line
;BrowseMapLong=+21.23

;Initial zoom level on Browse map,   e.g. 45000000 for Globe view
BrowseZoom=45000000

;Enable route computing after restart. Applicatio will compute the last computed route.
RouteComp=enable
; Set to true, if menus are operated by hardware buttons
; If set to true, then menus apear with pre-selected first item
; menuCursor = true | false (default)| autodetect
menuCursor=autodetect

; Sets style of keyboards: "visible" keyboards are for touch screens,
;   "cursor" keyboards are for remote-control operated black boxes, and
;   "invisible" keyboards are for mobile phones with their own hardware keyboard
; VISIBLE (normal)
; CURSOR (normal+arrows, small keyboard)
; INVISIBLE (dialog buttons)
; AUTODETECT ( if HW keyboard is detected = invisible, if not = visible)
keyboard=autodetect

; System timezone (GMT + timezone = your domestic time), specify time shift in minutes (e.g. -180 for GMT-3h)
; Used for time synchronization
; Enter one of the values from Skin\timezone.ini
timezone=-03:00_a

; hasClock=true (The device does have internal clock source, default) | false (compute clock from GPS GMT time and specified timezone)
hasClock=true
; if autosync=true, system time is set after first valid fix from gps time
; hasClock=true && autosync=true - only system time , system time set from gps after fix
; hasClock=true && autosync=false - only system time
; hasClock=false && autosync=true - system time + time zone, system time set from gps after fix
; hasClock=false && autosync=false - gps time + time zone
autosync=false


recommendedRam=10.0
; Set TTS modul
; Path to the Nuance modul
; Type 1 - Nuance; 2 - Acapela
; Format:LH= 0,SAMPAUCL = 1,IPA = 2,Nuance= 3,StarRecSAMPA= 4

[TTS]
Path=RealSpeakSolo
Type=2
Format=1